✨ Feature/webhook verification
SatelCreative/spylib pull request #113
Opened 2022-04-19 23:27 UTC by lishanl

fix #110 

- rename hmac functions param `is_base64` to `use_base64`
- add `verify_webhook` function
- add tests

2022-04-19 23:48 UTC, hillairet requested changes
Because you changed the arguments of a couple of functions, you should probably use a breaking change emoji for the PR title.

2022-04-19 23:48 UTC, hillairet commented on spylib/token.py
> +def verify_webhook(data: str, hmac_header: str, api_secret_key: str) -> bool:
If you return a boolean, I think a better name would be this:
```suggestion
def is_webhook_valid(data: str, hmac_header: str, api_secret_key: str) -> bool:
```

This way one can have a readable if statement:
```python
if is_webhook_valid():
```

2022-04-21 18:06 UTC, hillairet approved these changes
Cool stuff!

2022-04-21 18:34 UTC, qw-in approved these changes
Awesome thanks @lishanl! Excited to rip out our custom webhook code

2022-04-21 18:39 UTC, merged