:sparkles: [oauth] Add oauth hmac signature validation function
SatelCreative/spylib pull request #147
Opened 2022-06-09 20:44 UTC by qw-in

2022-06-10 18:07 UTC, hillairet requested changes
Since this is part of a refactoring effort it would be good each time to not just add/rewrite code but also remove and/or integrate with existing code.
In that case it seems that this new function should be called [here](https://github.com/SatelCreative/spylib/blob/a27d1ea99d2ad65b6ff272aa26397ce2b211130f/spylib/oauth/validations.py#L21)
Maybe we'll reorganize the `validate_callback` code later on but at least we don't have the same process/validation implemented twice with different performance (the existing one doesn't handle the `ids` case but yours does).

2022-06-10 18:07 UTC, hillairet commented on spylib/oauth/signature_validation.py
> +def parse_signed_query_string(query_string: str) -> SignedQueryString:
How about converting this to a class method of SignedQueryString? Seems more organized.
Then you simplify the naming:
```python
parsed = SignedQueryString.parse(query_string)
```

2022-06-13 19:22 UTC, qw-in commented
@hillairet @lishanl coming back to this, I am actually wondering if exporting anything other than `validate_*` is a mistake?

Maybe the parse fn could simply be merged into the validate one? That way we lower the API surface area? Let me know what you think!

2022-06-13 21:27 UTC, hillairet commented
Another point we need to clarify for the library as a whole.
I'd say KISS, so we expose less first because it's simpler then we expose if needed. Removing/changing API causes pain to the user and docs annoyance for us so better to have less but more stability.
We can expose more once we have reached some stability.

2022-06-21 02:05 UTC, lishanl commented on spylib/oauth/signature_validation.py
> +    message = urlencode(query_params, safe=':/').replace('ids=', f'ids={dumps(ids)}')
I am trying to understand what is the effect of `safe=':/'` here. Some explanation would be helpful.

2022-06-21 02:05 UTC, lishanl commented on spylib/oauth/signature_validation.py
> +    # can work as long as you pass `doseq=True` & `quote_via=quote``
is there an extra \` at the end of line? Instead of \`quote_via=quote`` -> \`quote_via=quote`?

2022-06-24 01:18 UTC, lishanl commented
> @hillairet @lishanl coming back to this, I am actually wondering if exporting anything other than `validate_*` is a mistake?
> 
> Maybe the parse fn could simply be merged into the validate one? That way we lower the API surface area? Let me know what you think!

Are you saying to just export `validate_signed_query_string` and do not export `SignedQueryString` and `parse_signed_query_string` via `spylib.oauth`? that sounds good, since `validate_signed_query_string` is probably mostly what the user needs. I wouldn't merge the parse fn into the validate one though. I prefer small and focused functions.

2022-06-24 21:18 UTC, lishanl commented
> Another point we need to clarify for the library as a whole. I'd say KISS, so we expose less first because it's simpler then we expose if needed. Removing/changing API causes pain to the user and docs annoyance for us so better to have less but more stability. We can expose more once we have reached some stability.

We could prefix the private methods / functions with `__` to indicate those are not to be accessed

2022-06-24 21:25 UTC, qw-in commented
> We could prefix the private methods / functions with `__` to indicate those are not to be accessed 

One of my bigger gripes with Python is that everything is "exported" by default. Wish there was like an `export` keyword or something

2022-06-27 15:14 UTC, hillairet commented
Single `_` would be enough. The double `__` is only enforced by the interpreter on class variables.

So moving the parsing to a classmethod, we'd have `_SignedQueryString` to indicate that it's internal and could change anytime. We could remove the underscore later on.

2022-06-27 19:52 UTC, qw-in commented
Ok, so I ended up just removing the parse fn - can always move the code back if it ends up being needed but the validate fn is a fine length imo.

Noticed in `oauth/validations.py` it attempts to handle sorting query string so I didn't want to remove that code and potentially break that behaviour. (seems like a workaround for a bonnette bug). Thoughts on how to handle?

2022-06-27 23:57 UTC, lishanl approved these changes
cool, thanks Quinn!

2022-06-28 15:44 UTC, hillairet approved these changes

2022-06-28 16:47 UTC, merged