Remove environment variables
SatelCreative/spylib pull request #45
Opened 2021-10-26 18:40 UTC by Nathan-Nesbitt

This removes the environment variable dependency from the library based on issue #25 . The logic for why this was done was:

1. *It is confusing to have environment variables in a library*:  You need to be super clear that they need to be set in the README, and you need to reflect these requirements in every new library / package that uses it.
2. *It limits the flexibility for the programmer*: I found that I would often need access to these variables, as they were defined in the library and not the app I would have to re-implement the code that was already done in spylib
3. *Conflicts*: If you have 2 libraries with the same variable name you are going to have problems as you won't be able to just change the env variable name as it is defined in the spylib library.

This is done by passing in the required environment variables to the oauth init function. 

https://github.com/SatelCreative/satel-spylib/blob/8c6686da95f6bcb9af4bbe8725dd66df8343ba97/spylib/oauth/router.py#L25-L37

Which later distributes the variables to other functions.

https://github.com/SatelCreative/satel-spylib/blob/8c6686da95f6bcb9af4bbe8725dd66df8343ba97/spylib/oauth/tokens.py#L18-L19

2021-10-26 18:56 UTC, hillairet requested changes
Code looks great.
How about a little migration warning in the README for migrating to 0.3? Cause that's a breaking change, and not a small one.

2021-10-27 18:07 UTC, hillairet requested changes
Ok let's get this right in terms of docs.
Let's add how to get the App handle as described [here].(https://github.com/SatelCreative/st-pim/blob/9c31fbc6f6738e16444ea7d5cbb7fd0a2f063e32/server/config.sh.example#L9)
Also We should make the handle an optional parameter. But I can't find where to redirect to without it ... weird! Let's do that in another PR though.

2021-10-27 18:07 UTC, hillairet commented on README.md
> +conf = ShopifyEnvironment()
We don't need to tell people how to manage their environment variables.
```suggestion
```

2021-10-27 18:07 UTC, hillairet commented on README.md
> +    app_handle=conf.handle,
```suggestion
    api_key='SHOPIFY_APP_API_KEY',
    api_secret_key='SHOPIFY_APP_SECRET_KEY',
    app_handle='SHOPIFY_APP_HANDLE',
```

2021-10-28 17:08 UTC, Nathan-Nesbitt commented
Created an issue for the optional handle @hillairet and fixed the rest!

2021-10-29 22:15 UTC, hillairet approved these changes
Cool let's push this through now.

2021-11-01 16:19 UTC, merged