App Proxy Utils
SatelCreative/spylib pull request #50
Opened 2021-11-02 19:08 UTC by Nathan-Nesbitt

This provides a middle-ware solution to the app proxy HMAC check.

2021-11-02 23:10 UTC, hillairet requested changes
**These aren't small changes**. Whole code sections are removed.
What issue is being fixed??? The code looks broken to me.
The message is made out of the query arguments MINUS the `hmac` query arguments cause the hmac can't encode itself ... The management of this trick is now gone for no good reason.

2021-11-02 23:10 UTC, hillairet commented on spylib/utils/hmac.py
> +    message_hmac = calculate_message_hmac(secret, body, is_base64)
Named arguments are preferred so it clearer and less error prone
```suggestion
    message_hmac = calculate_message_hmac(secret=secret, message=message, is_base64=is_base64)
```

2021-11-04 16:43 UTC, Nathan-Nesbitt commented on spylib/oauth/validations.py
> -    validate_hmac(secret=api_secret_key, sent_hmac=hmac_arg, message=message)
This functionality in this function was moved to `hmac.py` as the `validate_hmac` function wasn't doing anything before.

2021-11-04 16:58 UTC, Nathan-Nesbitt commented
@hillairet my newest change might explain why I made the changes to the HMAC function. Because the OAuth HMAC and the Proxy HMAC are so similar, I was trying to condense the existing code into 1 function instead of 2.

2021-11-04 19:25 UTC, hillairet requested changes
This is the part of SPyLib that requires the best and most tests. So let's get it right.

The best might be to write some unit tests for the validation and HMAC calculation functions BEFORE changing the code. I should be in another PR merged onto main.
You could open another PR, make only tests on the old code, unit tests different from the one in this PR, then refactor.

Having a mistake in this part of the code means that the package is totally useless.

2021-11-04 19:25 UTC, hillairet commented on tests/utils/test_app_proxy.py
> +    signature = calculate_message_hmac(API_SECRET, params)
You shouldn't use our code to make the fixture that will test our code ... you are just checking consistency here, not accuracy!
Either copy paste values straight from Shopify or calculate them yourself "manually" with a different code once and hardcode here.
The first option is best but can be annoying to get.

2021-11-04 19:25 UTC, hillairet commented on spylib/utils/app_proxy.py
> +        # As middleware is run on everyt(hing, this allows us to avoid checking on
```suggestion
        # As middleware is run on everything, this allows us to avoid checking on
```

2021-11-05 16:17 UTC, Nathan-Nesbitt commented
Totally makes sense @hillairet I will write some tests and come back to this when they get merged!

2021-11-25 19:02 UTC, Nathan-Nesbitt commented
Created new tests for HMAC in #63, will continue once merged.

2021-11-27 00:09 UTC, Nathan-Nesbitt commented
@hillairet Do you know why we have a base64 check in the function? I can't seem to find any reference to it being used in the code, and if it isn't being used I think it might be best to remove this function:

https://github.com/SatelCreative/satel-spylib/blob/c9a02f148c6df662e229c8605db5f376b95a61ed/spylib/utils/hmac.py#L7-L14

If we need the base64 code, we can just check to see if it is base64, and handle it accordingly. This is because it is essentially just a function around another function without the base64 check.

Can we also move the following function to `oauth/validations.py`:

https://github.com/SatelCreative/satel-spylib/blob/c9a02f148c6df662e229c8605db5f376b95a61ed/spylib/utils/hmac.py#L16-L24

In the main branch, it isn't really a generic hmac function as it is very specific to the format of the oauth token. I've modified it in this PR to be more generic, but I think it might be preferable to just have the oauth code handle the parsing?


**I will do this in a different issue and PR, then come back to this if you are okay with them.** I just think it will make it way clearer what is actually going on (and will allow me to reduce this PR to like 50 lines instead of 150)

2021-11-29 18:39 UTC, hillairet commented
@Nathan-Nesbitt So I found this base64 thing ... it's because the [webhook HMAC is base64 encoded](https://shopify.dev/apps/webhooks/https#verify-the-request-is-from-shopify)!

I have code that had a parameters `is_webhook` instead and I probably renamed to `is_base64` in case some other HMAC validation used a base 64. I can't think or find of one right now.
Should we pass an enum instead?

2021-12-01 21:35 UTC, Nathan-Nesbitt commented
> @Nathan-Nesbitt So I found this base64 thing ... it's because the [webhook HMAC is base64 encoded](https://shopify.dev/apps/webhooks/https#verify-the-request-is-from-shopify)!
> 
> I have code that had a parameters `is_webhook` instead and I probably renamed to `is_base64` in case some other HMAC validation used a base 64. I can't think or find of one right now. Should we pass an enum instead?

Okay should we have a parser for the webhook and the oauth which just handle this specific case? As I feel like this would be more clear if we just handle the base64 encoding in the specific instance (as it almost self documents that webhook HMAC are encoded) instead of having a shared function that tries to handle all the cases. Something like this?

**oauth/validations.py**
```python
def parse(message: Dict[str, list]):
    message.pop('hmac')[0]
    return '&'.join([f'{arg}={",".join(message[arg])}' for arg in message.keys()])

def validate(secret: str, hmac_actual: str, message: str):
    hmac_hash = hmac.new(secret.encode('utf-8'), message.encode('utf-8'), sha256).hexdigest()
    return hmac.compare_digest(hmac_actual, hmac_hash):
        
```

And we could have the following for the webhook handler in something like `utils/webhooks.py`:

```python
def validate(message: str):
    # Code for getting body of request
    hmac_header = request.headers.get('X-Shopify-Hmac-SHA256')
    digest = hmac.new(SECRET, data.encode('utf-8'), hashlib.sha256).digest()
    computed_hmac = base64.b64encode(digest)
    return hmac.compare_digest(computed_hmac, hmac_header.encode('utf-8'))
```

2021-12-02 00:30 UTC, hillairet commented
I like it!
Indeed if it's only in webhooks as far as we know, let's keep the base64 in the webhook code.

2022-02-23 00:57 UTC, lishanl commented
Do we want to wrap this PR? @hillairet Do you want to pick it up from here or you have other suggestions?

2022-02-28 16:40 UTC, hillairet commented
There is some interesting clean up and new code here but we would do better with some planning and organizing from scratch I think.
I'd like some more input on the best way to organize the hmac validation actually.

2022-02-28 16:40 UTC, closed without merging