Add 3.8 and 3.10 to tests
SatelCreative/spylib pull request #79
Opened 2022-01-24 20:46 UTC by Nathan-Nesbitt

2022-01-24 23:02 UTC, Nathan-Nesbitt commented
@rahulpatidar0191 any idea how to fix the missing windows binary issues displayed in the tests?

2022-01-24 23:19 UTC, hillairet commented
Weird error.
Don't worry too much about Windows.
We can remove the windows test for now if needed and add them back later. Better to have more python versions tested.

2022-01-25 17:59 UTC, Nathan-Nesbitt commented
@hillairet I think this is an error with mypy and just Windows with python 3.10 as 3.9 still works. I'll remove windows for now

2022-01-25 17:59 UTC, Nathan-Nesbitt commented
3.8 might be an issue, as many of our dependencies are not compatible with 3.8 should we keep them?

2022-01-26 17:42 UTC, hillairet requested changes
Ok sweet: we learned that our current set of dependencies are not compatible with python 3.8! And that's good to know.
Fine for now. We can make an issue to try to recover the compatibility if possible.

Could you make a note in the README somewhere towards the top?
Also it'd be nice to have a badge in the README to show which versions work. We could potentially have a red badge for 3.8 ...
If it's easy to do the badge, do it, otherwise we'll do it later.

2022-02-09 16:27 UTC, hillairet requested changes

2022-02-09 16:27 UTC, hillairet commented on tox.ini
> +    3.10: py310, flake8, mypy, black
The static code analysis shouldn't be python version dependent. Let's just run it for the latest python.
We only need to run pytest for each python version:
```suggestion
    3.8: py38
    3.9: py39
    3.10: py310, flake8, mypy, black
```

2022-02-09 16:33 UTC, hillairet approved these changes

2022-02-09 17:35 UTC, merged

2022-02-09 23:34 UTC, lishanl commented on tox.ini
> +    3.10: py310, flake8, mypy, black
right, I remembered you said something about this but didn't remember what exactly, so this is it. 🆒