:bug: Fix tests to prevent pytest from hanging
SatelCreative/spylib pull request #98
Opened 2022-03-11 21:52 UTC by hillairet

It looks like it was some old "standard" code that I can't remember why we needed it before but I suspect that the pytest async library is now doing what the conftest file was doing before.

Locally the problem is fixed for python 3.10

2022-03-11 22:12 UTC, qw-in approved these changes
Assuming you checked with 0.68 and below right? Nice job!

2022-03-11 22:40 UTC, hillairet commented
@jsemearns I keep thinking this is Slackers so I put you as reviewer at first. Feel free to review though!  :wink:

2022-03-11 22:44 UTC, hillairet commented
> Assuming you checked with 0.68 and below right? Nice job!

Oh no I didn't think of that. It does not work ... :persevere: 
But I don't see a problem with requiring `>= 0.69.0`.
Do you foresee any issue? The version 0.69.0 is 5 months old now ...

2022-03-11 23:46 UTC, lishanl approved these changes
Hard to see the interrelations, another good reason to identify and remove the unnecessary dependency

2022-03-12 01:06 UTC, qw-in requested changes
Yeah, I don't see any issues. As long as we release it as `0.5` or something and note the breaking change

2022-03-12 01:06 UTC, qw-in commented on pyproject.toml
> +fastapi = ">= 0.65.1"
```suggestion
fastapi = ">= 0.69.0"
```

2022-03-12 06:53 UTC, hillairet commented on pyproject.toml
> +fastapi = ">= 0.65.1"
Definitely 0.5

2022-03-14 23:49 UTC, qw-in approved these changes

2022-03-15 16:22 UTC, merged